repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-executable==2.1.3
          - bandit==1.7.4
          - flake8-bugbear==21.11.29
          - flake8-comprehensions==3.10.1
        args: [ "--max-line-length", "120" ]
        exclude: "tests/to-be-tested/"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
        files: ^flake8_executable
        exclude: "tests/"
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        exclude: "tests/to-be-tested/"
